### ISSUE TITLE
f-user-message: Optimise bundle size

### ISSUE THREAD

**Issue by zlatinivanov-je** [justeattakeaway/fozzie-components#160]
_Observation:_
f-user-message build reports bundle size: 278.83 KB minified, 70kb gzipped. 
That seems excessive considering it is a single vue component and does not contain images or content. 

**Task:** 
Optimise bundle size.

**Comment by dandel10n** [comment]
@zlatinivanov-je can we close this issue now as the changes were merged as I can see?
