### ISSUE TITLE
f-vue-icons – Releasing v1

### ISSUE THREAD

**Issue by ashleynolan** [justeattakeaway/fozzie-components#207]
Just making this list as a checklist for releasing the v1 branch (currently in [beta here](https://github.com/justeat/fozzie-components/tree/f-vue-icons%40v1.0.0)).

- [ ] icon location SVG (used in f-searchbox) should be included
- [x] handling colours should be looked at and a solution found for when upgrading

**Comment by DamianMullins** [comment]
@ashleynolan Can we close the second point off as we've decided that the styles should in the consuming package?

**Comment by dandel10n** [comment]
Closing as completed
