### ISSUE TITLE
f-footer - Country selector contrast

### ISSUE THREAD

**Issue by xander-marjoram** [justeattakeaway/fozzie-components#261]
From Lighthouse: 
> Background and foreground colors do not have a sufficient contrast ratio.

On element:
`<span data-test-id="countrySelector-current-country"> United Kingdom </span>` 

Suggest setting `color: $color-text`

![20200728T152030](https://user-images.githubusercontent.com/26894168/88678030-ebc70b80-d0e5-11ea-972e-cc4b2474db67.png)

**Comment by dandel10n** [comment]
This has been fixed
