### ISSUE TITLE
Imported f-footer CSS overrides project CSS

### ISSUE THREAD

**Issue by DamianMullins** [justeattakeaway/fozzie-components#42]
When importing the f-footer css into a project classes they can override any existing styles, such as [the c-icon--chevron class in the `LinkList.vue` component](https://github.com/justeat/fozzie-components/blob/a067f18a33d5a956c470403befe20a1ea5767e1e/packages/f-footer/src/components/LinkList.vue#L170-L173), which overrides the style set within Fozzie and causes _all_ chevron icons to become 16x9px.

Could we look at using CSS modules in our shared components in order to prevent styles from affecting others around them? CSS modules can be enabled by adding the `module` attribute to the `style` tag (`<style module>`).

I think we've briefly discussed scoped CSS vs CSS modules in the past and were leaning more towards CSS modules as the styles don't allow styles to leak down to child components. 

[This blog post](https://www.netguru.com/codestories/vue.js-scoped-styles-vs-css-modules) describes the two approaches really well.

I can put together a PR to test with if that's OK?

**Comment by dandel10n** [comment]
@DamianMullins modules solution sounds great :+1:

**Comment by DamianMullins** [comment]
I'll have a look at that this afternoon.
